### ISSUE TITLE
Tuya water leakage detector with Tasmota

### ISSUE THREAD

**Issue by pippopitbull** [aZholtikov/ESP-NOW-Water-Leakage-Sensor#1]
Hello, I bought this Tuya sensor and I'm looking for Tasmota configuration.I replaced the chip with an ESP8266 and I installed Tasmota.
![image](https://github.com/aZholtikov/ESP-NOW-Water-Leakage-Sensor/assets/112604071/64055fad-4fb5-4493-84bb-71c62b31276b)

![image](https://github.com/aZholtikov/ESP-NOW-Water-Leakage-Sensor/assets/112604071/5ad79770-580f-4a8c-915c-06aad754ce93)

![image](https://github.com/aZholtikov/ESP-NOW-Water-Leakage-Sensor/assets/112604071/a5b9a7fc-a7a6-4229-bace-895d915991c7)

**Comment by aZholtikov** [comment]
The Tasmota firmware uses a WiFi connection. It takes a long time to connect to the network. The battery drains quickly.
The ESP-NOW protocol does not have this problem.

**Comment by pippopitbull** [comment]
Thanks for the info, has anyone already programmed this model of water sensor with esp-now? I have no idea how to program the GPIO.

**Comment by aZholtikov** [comment]
This particular model has already been purchased and is on my "waiting list" to be re-flashed to ESP-NOW. Please wait updates. But I can't promise a quick update...
![IMG_2264](https://github.com/aZholtikov/ESP-NOW-Water-Leakage-Sensor/assets/57955179/547a206a-f2d8-44d6-8f3f-dc250cf57a9c)

**Comment by pippopitbull** [comment]
Thank you!!!!!!
